# Generated by Django 4.2.1 on 2023-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fno-image-available&psig=AOvVaw0QZ3Z2Z4Z4Z4Z4Z4Z4Z4Z4&ust=1602178970002000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJjQ4ZqH_-wCFQAAAAAdAAAAABAD', null=True),
        ),
    ]
